use_vllm: true
vllm_mode: colocate
# vllm_max_model_len: 2048 # Apparently this is overriden by max_prompt_len + max_completion_len
vllm_enable_sleep_mode: true
output_dir: GRPO
learning_rate: 0.00005
max_prompt_length: 512
optim: adamw_8bit
num_train_epochs: 2
fp16: true
bf16: false
save_steps: 100
logging_steps: 1
max_completion_length: 2048

num_generations: 8
per_device_train_batch_size: 4
gradient_accumulation_steps: 1

# Random seed for reproducibility
# Can be overridden via CLI: train.seed=42
seed: 50
data_seed: ${train.seed}
